name: Dispatch on Release

on:
  release:
    types: [published]

jobs:
  dispatch:
    - name: Dispatch repository_dispatch event
      uses: ph-fritsche/action-dispatch@v1
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        type: repository
        ident: repo_test_update # refer to on.repository_dispatch.types.*
