name: "Move Latest Commit to PR"
description: "Removes the latest commit from the history and moves it to a Pull Request"
author: "mail@fabriziocacicia.com"

inputs:
  prTitle:
    description: 'The title of the PR'
    required: false
    default: ''
  prBody:
    description: 'The body of the PR'
    required: false
    default: ''
  baseBranch:
    description: 'The branch to which the PR will merge'
    required: false
    default: 'main'
  headBranch:
    description: 'The base name of the branch that creates the PR. It will be suffixed by the latest commit hash (i.e. branch_name/hash). If not set the head branch name will be the latest commit has only.'
    required: false
    default: ''
  assignee:
    description: 'The assignee of the Pull Request. The defualt value is the author of the latest commit.'
    required: false
    default: ${{ github.actor }}
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Prepare Pull Request
      id: prepare_pr
      run: |
        LATEST_COMMIT_HASH=$(git log -1 --format=%h)
        
        
        if [ -z "${{ inputs.prTitle }}" ]       
        then
          LATEST_COMMIT_MESSAGE=$(git log -1 --format=%B)
          PR_TITLE=$LATEST_COMMIT_MESSAGE
        else
          PR_TITLE=$(${{ inputs.prTitle }})
        fi
        echo "::set-output name=PR_TITLE::$PR_TITLE"
        
        
        if [ -z "${{ inputs.prBody }}" ]
        then
          PRBODY="The commit $LATEST_COMMIT_HASH has been removed from the repository history and moved to this Pull Request.
          
            Auto-generated by [move-latest-commit-to-rp][1]
            [1]: https://github.com/peter-evans/create-pull-request"
        else
          PRBODY="${{ inputs.prBody }}"
        fi
        PRBODY="${PRBODY//'%'/'%25'}"
        PRBODY="${PRBODY//$'\n'/'%0A'}"
        PRBODY="${PRBODY//$'\r'/'%0D'}"
        echo "::set-output name=PRBODY::$PRBODY"
        
        
        if [ -z "${{ inputs.headBranch }}" ]
        then
          HEAD_BRANCH_NAME="$LATEST_COMMIT_HASH"
        else
          HEAD_BRANCH_NAME="${{ inputs.headBranch }}/$LATEST_COMMIT_HASH"
        fi            
        echo "HEAD_BRANCH_NAME=$HEAD_BRANCH_NAME" >> $GITHUB_ENV
        
        
        chmod +x $GITHUB_ACTION_PATH/create_new_branch.sh
        $GITHUB_ACTION_PATH/create_new_branch.sh -b $HEAD_BRANCH_NAME
      shell: bash
    - run: git checkout main
      shell: bash
    - name: Undo Last Commit
      uses: fabriziocacicia/undo-latest-commit-action@v0.1.0
    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh pr create --title "${{ steps.prepare_pr.outputs.prtitle }}" --base ${{ inputs.baseBranch }} --head ${{ env.HEAD_BRANCH_NAME }} --assignee ${{ inputs.assignee }} --body "${{ steps.prepare_pr.outputs.prbody }}"
      shell: bash
