name: "Move Latest Commit to PR"
description: "Removes the latest commit from the history and moves it to a Pull Request"
author: "mail@fabriziocacicia.com"

inputs:
  prTitle:
    description: 'The title of the PR'
    required: false
    default: ''
  prBody:
    description: 'The body of the PR'
    required: false
    default: ''
  headBranch:
    description: 'The branch that creates the PR'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create New Branch
      run: |
        LATEST_COMMIT_HASH=$(git log -1 --format=%h)
        echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH" >> $GITHUB_ENV
        
        if [ -z "${{ github.event.inputs.prTitle }}" ]       
        then
          COMMIT_MESSAGE=$(git log -1 --format=%B)
        else
          COMMIT_MESSAGE=${{ github.event.inputs.prTitle }}
        fi
        if [ -z "${{ github.event.inputs.prBody }}" ]
        then
          PRBODY="The commit $LATEST_COMMIT_HASH doesn't follow the [Conventional Commit convention].
          > Because of that, it was removed from the history of the repository.
          > Please, squash this PR updating the commit message so that it follows the convention.
          > Auto-generated by [keep-history-conventional][1]
          > [1]: https://github.com/peter-evans/create-pull-request"
        else
          PRBODY="${{ github.event.inputs.prBody }}"
        fi
        if [ -z "${{ github.event.inputs.headBranch }}" ]
        then
          NEW_BRANCH_NAME="keep_history_conventional/$LATEST_COMMIT_HASH"
        else
          NEW_BRANCH_NAME="${{ github.event.inputs.headBranch }}"
        fi        
        
        echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
        echo "PRBODY=$PRBODY" >> $GITHUB_ENV
        
        chmod +x $GITHUB_ACTION_PATH/prepare_pr.sh
        $GITHUB_ACTION_PATH/prepare_pr.sh -b $NEW_BRANCH_NAME
      shell: bash
    - run: git checkout main
      shell: bash
    - name: Undo Last Commit
      uses: fabriziocacicia/undo-latest-commit-action@v0.1.0
    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh pr create --title "${{ env.COMMIT_MESSAGE }}" --base main --head ${{ env.NEW_BRANCH_NAME }} --assignee ${{ github.actor }} --body "${{ env.PRBODY }}"
      shell: bash
