name: "Move Latest Commit to PR"
description: "Removes the latest commit from the history and moves it to a Pull Request"
author: "mail@fabriziocacicia.com"

inputs:
  prTitle:
    description: 'The title of the PR'
    required: false
    default: ''
  prBody:
    description: 'The body of the PR'
    required: false
    default: ''
  headBranch:
    description: 'The branch that creates the PR'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create New Branch
      id: prepare_pr
      run: |
        LATEST_COMMIT_HASH=$(git log -1 --format=%h)
        echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH" >> $GITHUB_ENV
        
        if [ -z "${{ inputs.prTitle }}" ]       
        then
          COMMIT_MESSAGE=$(git log -1 --format=%B)
        else
          COMMIT_MESSAGE=${{ inputs.prTitle }}
        fi
        if [ -z "${{ inputs.prBody }}" ]
        then
          PRBODY="The commit $LATEST_COMMIT_HASH has been remove from the repository history and moved to this Pull Request.
          
            Auto-generated by [move-latest-commit-to-rp][1]
            [1]: https://github.com/peter-evans/create-pull-request"
        else
          PRBODY="${{ inputs.prBody }}"
        fi
        if [ -z "${{ inputs.headBranch }}" ]
        then
          NEW_BRANCH_NAME="keep_history_conventional/$LATEST_COMMIT_HASH"
        else
          NEW_BRANCH_NAME="${{ inputs.headBranch }}"
        fi        
        
        echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
        PRBODY="${PRBODY//'%'/'%25'}"
        PRBODY="${PRBODY//$'\n'/'%0A'}"
        PRBODY="${PRBODY//$'\r'/'%0D'}"
        echo "::set-output name=PRBODY::$PRBODY"
        
        chmod +x $GITHUB_ACTION_PATH/prepare_pr.sh
        $GITHUB_ACTION_PATH/prepare_pr.sh -b $NEW_BRANCH_NAME
      shell: bash
    - run: git checkout main
      shell: bash
    - name: Undo Last Commit
      uses: fabriziocacicia/undo-latest-commit-action@v0.1.0
    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh pr create --title "${{ env.COMMIT_MESSAGE }}" --base main --head ${{ env.NEW_BRANCH_NAME }} --assignee ${{ github.actor }} --body "${{ steps.prepare_pr.outputs.prbody }}"
      shell: bash
