name: "Move Latest Commit to PR"
description: "Removes the latest commit from the history and moves it to a Pull Request"
author: "mail@fabriziocacicia.com"

inputs:
  prTitle:
    description: 'The title of the PR. (default is the message of the commit that will be moved)'
    required: false
  prBody:
    description: 'The body of the PR'
    required: false
  baseBranch:
    description: 'The branch to which the PR will merge. (default is the branch to which the commit to move belongs to)'
    required: false
  headBranch:
    description: 'The base name of the branch that creates the PR. It will be suffixed by the latest commit hash (i.e. branch_name/hash). (default is the hash of the latest commit)'
    required: false
  assignee:
    description: 'The assignee of the Pull Request. (defualt value is the author of the latest commit)'
    required: false
    default: ${{ github.actor }}
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - name: Set baseBranch
      id: base_branch
      run: |
        base_branch=${{ inputs.baseBranch }}
        
        if [ -z $base_branch ]; then
          base_branch=${{ steps.branch-name.outputs.current_branch }}
        fi
        echo "::set-output name=value::$base_branch"
      shell: bash    
    - name: Set prTitle
      id: pr_title
      run: |
        pr_title=${{ inputs.prTitle }}
        
        if [ -z $pr_title ]; then
          LATEST_COMMIT_MESSAGE=$(git log -1 --format=%B)
          pr_title=$LATEST_COMMIT_MESSAGE
        fi
        echo "::set-output name=value::$pr_title"
      shell: bash    
    - name: Prepare Pull Request
      id: prepare_pr
      env:
          AFTER_HASH: ${{ github.event.after }}
      run: |
        LATEST_COMMIT_HASH=$(git log -1 --format=%h)
        
        if [ -z "${{ inputs.prBody }}" ]
        then
          PRBODY="The commit $LATEST_COMMIT_HASH has been removed from the repository history and moved to this Pull Request.
          
            Auto-generated by [move-latest-commit-to-pr][1]
            [1]: https://github.comfabriziocacicia/move-latest-commit-to-pr"
        else
          PRBODY="${{ inputs.prBody }}"
        fi
        PRBODY="${PRBODY//'%'/'%25'}"
        PRBODY="${PRBODY//$'\n'/'%0A'}"
        PRBODY="${PRBODY//$'\r'/'%0D'}"
        echo "::set-output name=PRBODY::$PRBODY"
        
        
        if [ -z "${{ inputs.headBranch }}" ]
        then
          HEAD_BRANCH_NAME="$LATEST_COMMIT_HASH"
        else
          HEAD_BRANCH_NAME="${{ inputs.headBranch }}/$LATEST_COMMIT_HASH"
        fi            
        echo "::set-output name=HEAD_BRANCH_NAME::$HEAD_BRANCH_NAME"
        
        
        chmod +x $GITHUB_ACTION_PATH/create_new_branch.sh
        $GITHUB_ACTION_PATH/create_new_branch.sh -b $HEAD_BRANCH_NAME
      shell: bash
    - run: git checkout ${{ steps.base_branch.outputs.value }}
      shell: bash
    - name: Undo Last Commit
      uses: ./undo_commit_action
    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh pr create --title "${{ steps.pr_title.outputs.value }}" --base ${{ steps.base_branch.outputs.value }} --head "${{ steps.prepare_pr.outputs.head_branch_name }}" --assignee ${{ inputs.assignee }} --body "${{ steps.prepare_pr.outputs.prbody }}"
      shell: bash
