name: "Keep History Conventional"
description: "Github Action that keep in the Github commits history only the ones that follow the Conventional Commit convention."
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check Latest Commit Conventional
      uses: fabriziocacicia/check-latest-commit-conventional-action@v0.1.0
      id: check-conventional-commit
      continue-on-error: true
    - if: steps.check-conventional-commit.outcome == 'success'
      run: exit 0
      shell: bash
    - name: Move Latest Commit to PR
      if: steps.check-conventional-commit.outcome != 'success'
      uses: ./move-latest-commit-to-pr
      with:
        prBody: |
          The commit asd doesn't follow the [Conventional Commit convention](https://www.conventionalcommits.org/). 
          Because of that, it was removed from the history of the repository.
         
          Please, squash this PR updating the commit message so that it follows the convention.
          
          - Auto-generated by [keep-history-conventional][1]
    
          [1]: https://github.com/peter-evans/create-pull-request
    #- name: Create New Branch
    #  if: steps.check-conventional-commit.outcome != 'success'
    #  run: |
    #    LATEST_COMMIT_HASH=$(git log -1 --format=%h)
    #    echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH" >> $GITHUB_ENV
    #    NEW_BRANCH_NAME="keep_history_conventional/$LATEST_COMMIT_HASH"
    #    echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
    #    COMMIT_MESSAGE=$(git log -1 --format=%B)
    #    echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
    #    chmod +x $GITHUB_ACTION_PATH/prepare_pr.sh
    #    echo $NEW_BRANCH_NAME
    #    $GITHUB_ACTION_PATH/prepare_pr.sh -b $NEW_BRANCH_NAME
    #  shell: bash
    #- if: steps.check-conventional-commit.outcome != 'success'
    #  run: git checkout main
    #  shell: bash
    #- name: Undo Last Commit
    #  if: steps.check-conventional-commit.outcome != 'success'
    #  uses: fabriziocacicia/undo-latest-commit-action@v0.1.0
    #- name: Create Pull Request
    #  if: steps.check-conventional-commit.outcome != 'success'
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
    #  run: |
    #    gh pr create --title "${{ env.COMMIT_MESSAGE }}" --base main --head ${{ env.NEW_BRANCH_NAME }} --assignee ${{ github.actor }} --body "The commit ${{ env.LATEST_COMMIT_HASH }} doesn't follow the [Conventional Commit convention](https://www.conventionalcommits.org/)."
    #  shell: bash

branding:
  icon: "mic"
  color: "black"
