name: "Keep History Conventional"
description: "Github Action that keep in the Github commits history only the ones that follow the Conventional Commit convention."
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check Latest Commit Conventional
      uses: fabriziocacicia/check-conventional-latest-commit-action@v0.1.0
      id: check-conventional-commit
      continue-on-error: true
    - if: steps.check-conventional-commit.outcome == 'success'
      run: exit 0
      shell: bash
    - name: Prepare PR
      if: steps.check-conventional-commit.outcome != 'success'
      run: |
        chmod +x $GITHUB_ACTION_PATH/create_pr.sh
        $GITHUB_ACTION_PATH/create_pr.sh
        LATEST_COMMIT_HASH=$(git log -1 --format=%h)
        echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH" >> $GITHUB_ENV
        NEW_BRANCH_NAME="keep_history_conventional/$LATEST_COMMIT_HASH"
        echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
        COMMIT_MESSAGE=$(git log -1 --format=%B)
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
      shell: bash
    - name: Create Pull Request
      if: steps.check-conventional-commit.outcome != 'success'
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: ${{ env.COMMIT_MESSAGE }}
        committer: Keep History Conventional Action <keep-history-conventional-action[bot]@users.noreply.github.com>
        author: Keep History Conventional Action <keep-history-conventional-action[bot]@users.noreply.github.com>
        base: main
        branch: ${{ env.NEW_BRANCH_NAME }}
        delete-branch: true
        title: ${{ env.COMMIT_MESSAGE }}
        body: |
          The commit ${{ env.LATEST_COMMIT_HASH }} doesn't follow the [Conventional Commit convention](https://www.conventionalcommits.org/). 
          Because of that, it was removed from the history of the repository.
         
          Please, squash this PR updating the commit message so that it follow the convention.
          
          - Auto-generated by [keep-history-conventional][1]

          [1]: https://github.com/peter-evans/create-pull-request

branding:
  icon: "mic"
  color: "black"
