name: Check for Template new Release
on:
  workflow_dispatch:

jobs:
  check-for-template-new-release:
    if: ${{ vars.TEMPLATE_REPO }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Latest Template Release
        uses: octokit/request-action@v2.1.7
        id: get_latest_release
        with:
          route: GET /repos/${{ vars.TEMPLATE_REPO }}/releases/latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Print Latest Template Release
        shell: bash
        run: echo "${{ steps.get_latest_release.outputs.data }}"
      - name: Update template release value
        uses: octokit/request-action@v2.1.7
        id: update_template_release
        with:
          route: PATCH /repos/${{ github.repository}}/actions/variable/TEMPLATE_LATEST_RELEASE
          name: TEMPLATE_LATEST_RELEASE
          value: ${{ steps.update_template_release.outputs.data.name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
