name: Merge Template Changes
on:
  workflow_run:
    workflows: [Check for Template Updates]
    types:
      - completed

jobs:
  print_workflow_run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ fromJSON(github.event.workflow_run.repository) }}"
  on-new-changes:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-no-changes:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'skipped' }}
    steps:
      - run: echo 'The template has no new release'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The Check for Template Updates failed'
