name: Self Delete Workflow
on:
  workflow_dispatch

jobs:
  delete_tags_without_release:
    runs-on: ubuntu-latest
    steps:
      - name: Self Delete Workflow
        uses: fabriziocacicia/self-delete-workflow-action@v0.1.0-draft
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
