name: Shell
on:
  workflow_dispatch:

jobs:
  shell:
    name: Shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - run: echo $default-branch
        shell: bash
