name: Undo Commit
on:
  workflow_dispatch:

jobs:
  build:
    name: Undo Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - name: Undo Last Commit
        uses: fabriziocacicia/undo-latest-commit-action@v0.1.0
