name: Check Conventional Commit
on:
  push:

jobs:
  build:
    name: Undo Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - uses: dkhunt27/action-conventional-commits@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Undo Last Commit
      #  uses: fabriziocacicia/undo-latest-commit-action@v0.1.0
